<!DOCTYPE html>
<html>
    <head>
        <title>FlareGramster &bull; Oatmeal</title>
        <meta charset="UTF-8">
        <script>'article aside footer header main nav section time'.replace(/\w+/g,function(n){document.createElement(n)})</script>
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link href="/style/style<?php if ($settings['debugging'] == false) echo '-min'; ?>.css" rel="stylesheet" type="text/css" media="screen"></style>
        <?php foreach ($metaTags as $type => $group) { ?>
            <?php foreach ($group as $key => $value) { ?>
                <?php if ($value === null) continue; ?>
                <meta <?php echo $type; ?>="<?php echo $key; ?>" content="<?php echo htmlspecialchars($value); ?>">
            <?php } ?>
        <?php } ?>
    </head>
    <body>
        <div class="wrapper">
            <div id="content" class="center">
                <form action="/" method="post" enctype="multipart/form-data">
                    <input type="hidden" name="filter" value="">
                    <h1>Enter Image URL (size will be 612px by 612px)</h1>
                    <input type="url" name="url" value="http://i.imgur.com/XTBwBhB.jpg" class="dark-shadow">
                </form>
                <p id="progress"></p>
                <div id="image-container">
                    <?php if (isset($output)) { ?>
                        <img src="/output/<?php echo $output; ?>" id="result">
                    <?php } ?>
                    <div class="social">
                        <?php if (isset($socialForm)) { ?>
                            <form action="<?php echo $request->getPath(); ?>" method="post">
                                <textarea name="message" placeholder="Type in your message"></textarea>
                                <input type="submit" name="submit" value="Post Message">
                            </form>
                        <?php } else { ?>
                            <ul>
                                <?php $i = 0; ?>
                                <?php foreach ($settings['social'] as $name => $data) { ?>
                                    <li class="<?php echo $name; ?> <?php if ($i % 4 === 0) echo 'first'; ?>" title="Share on <?php echo $data['title']; ?>"><a href="<?php echo $oauth->getUri($name); ?>"></a></li>
                                    <?php $i++; ?>
                                <?php } ?>
                            </ul>
                        <?php } ?>
                    </div>
                </div>
            </div>
        </div>
        <div id="footer" class="center">
            <div class="wrapper">
                <h2>Orinigal implementation by  <a href="http://webarto.com" target="_blank">★ Webarto</a>. Moar awesomeness by <a href="https://github.com/PeeHaa" target="_blank">★ PeeHaa</a></h2>
            </div>
        </div>
        <script src="/js/main<?php if ($settings['debugging'] == false) echo '-min'; ?>.js"></script>
        <?php require_once __DIR__ . '/google-analytics.phtml'; ?>
    </body>
</html>
